# Baidu OCR service api
spring.custom.baidu.ocr.appId=ENC(9iQLvjYVmybI7KcqN8nyA+oY1VaO5SQY)
spring.custom.baidu.ocr.apiKey=ENC(CDzh+mP25K0BVq2BV0bCWulNhTA469bOlZmJDEa3DXA30+S9hcYyqQ==)
spring.custom.baidu.ocr.apiSecret=ENC(+iHSdi4NAis0ut7F5mvoNDhVgBK/r8FGpLHxsKV6kHCvoNl1t+p8cYei8C96iVaV)

# XunFei Spark LLM chat api
spring.custom.xf.spark.appId=ENC(JsAlGeQq0Md4FbqRDqp1rRFXJYWOErQp)
spring.custom.xf.spark.apiKey=ENC(XZZe7V9f+CqPK9S8ldI2gEMB2dw/w0M3gTCfbp3nfPZyAs6m/N14DVQNAX+b7feP)
spring.custom.xf.spark.apiSecret=ENC(MCLG01IXlfEP/F6jpqmuVg+Mnw25svSg2T7kNbB1OuAyREHcUoFGozyfbRLylhJk)

# Ali Tongyi LLM api
spring.custom.ali.tongyi.apiKey=sk-51e2c0a8805f421c9a1abcbe4148658b
# ByteDance volce LLM api
spring.custom.bytedance.volce.apiKey=ENC(AOJB0D/b5o5Yh6GuWQ8UzfRoS09ea2yMfczU84s/4xa25OJor9G0mBt/fiWx9Y7x1/vOq5hPz+s=)
spring.custom.bytedance.volce.apiSecret=ENC(lDZXyx2iUUvdV/cHjs/hLgmVjASIAx/APHlyagp1Y3i1hmxST5Kk3rEqNLBjqmjLGpQHYT/dUEK8j7NPbaLaF+lvKlTcB4ad)

# zhipu LLM api
spring.custom.zhipu.apiKey=ENC(vJjjem6Om5pK4UrRkBGiE3U/ueHhntBmI83EuiivVqaQepHfo25aHZWdCV8cVixj8KaYusjZxBD5TJD8Ckxrqg==)

# Baidu wenxin LLM api
spring.custom.baidu.wenxin.apiKey=ENC(Igh/7Ly1ZCCBGGCJQxholTHEDIjGFMcRQS7J/4GBmDBKrZ6KPClucg==)
spring.custom.baidu.wenxin.apiSecret=ENC(p1xP9oxsWy83UgOooGPRd1CFA6CUL+bO3DfhZ2TuHAkzezVVbvio4DdUPT3ZmZkU)

# rapid api key
spring.custom.juhe.api.newsApiKey=ENC(G2W3yu3CE7sTve6+i5f9p4QiiTEYs9UtU7sLYu58mBYEG6QD5sPGUO1DruJoQ4Gw)
spring.custom.juhe.api.weatherApiKey=ENC(E72KlOZpfwHdXyRPb2pxxFT9HBAmlQEXElQZKS74ynGsUOSIvu4IOosJXjlRTPXy)
spring.custom.juhe.api.fortuneApiKey=ENC(7f78sTK/qrzKCNufsBpZm719J38N5hjhMJ4rawP57NeTQh4cfZEvIiBULX33OEvK)
